services:
  php:
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html:cached

  nginx:
    volumes:
      - ./public:/var/www/html/public:ro

