# Use the MySQL base image
FROM mysql:8.0

# Environment variables can be set here or in the docker-compose file
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=symfony
ENV MYSQL_USER=symfony
ENV MYSQL_PASSWORD=symfony
