# config/services.yaml
imports:
    - { resource: './packages/payment.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    GuzzleHttp\Client.Aci:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%aci.base_uri%' }

    GuzzleHttp\Client.Shift4:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%shift4.base_uri%' }

    App\Service\PaymentStrategy\AciPaymentStrategy:
        arguments:
            - '@GuzzleHttp\Client.Aci'
            - '%aci.api_key%'
            - '%aci.payment_endpoint%'
        tags: ['payment_strategy']

    App\Service\PaymentStrategy\Shift4PaymentStrategy:
        arguments:
            - '@GuzzleHttp\Client.Shift4'
            - '%shift4.api_key%'
            - '%shift4.payment_endpoint%'
        tags: ['payment_strategy']

    App\Service\PaymentStrategy\PaymentStrategyFactory:
        arguments:
            $parameterBag: '@parameter_bag'
            $strategies:
                'shift4': App\Service\PaymentStrategy\Shift4PaymentStrategy
                'aci': App\Service\PaymentStrategy\AciPaymentStrategy

    App\Service\PaymentService:
        arguments:
            $logger: '@logger'
            $strategyFactory: '@App\Service\PaymentStrategy\PaymentStrategyFactory'
            $cache: '@cache.app'
            $validator: '@App\Service\PaymentDataValidator'

    App\Command\PaymentCommand:
        tags:
            - { name: 'console.command' }

    App\Controller\PaymentController:
        arguments:
            $paymentService: '@App\Service\PaymentService'

    App\Service\PaymentDataValidator:
        public: true

    # Register the custom CardNumber constraint validator
    App\Validator\CardNumberValidator:
        tags:
            - { name: 'validator.constraint_validator', alias: 'card_number_validator' }